/////MODELS//////
const models = {}
models.Пользователь                         = require('../models/user')
models.Студент                              = require('../models/student')
models.Направление                          = require('../models/napravlenie')
models.Учебные_дисциплины                   = require('../models/uchebnieDiscipliny')
models.Компетенция                          = require('../models/competencia')
models.Индикаторы_достижения_компетенций    = require('../models/indicatoryDostizheniyaCompetenciy')
models.Контрольные_задания                  = require('../models/controlnieZadaniya')
models.Оценки_кз                            = require('../models/ocenkyKZ')
models.Нечеткая_классфикация_зув            = require('../models/nechetkayaClassifikaciya')
models.Оценки_компетенций                   = require('../models/ocenkyCompetenciy')
models.Термы_и_область_определения          = require('../models/termy&oblastOpredeleniya')
models.Оценки_индикаторов                   = require('../models/ocenkyIndicatorov')
models.Функция_принадлежности               = require('../models/funciaPrinadlezhnosty')
models.Функция_принадлежности_терм          = require('../models/funciaPrinadlezhnostyTerm')
models.Результаты_обучения_зув              = require('../models/rezultatyObycheniyaZYV')
models.Индикатор_зув                        = require('../models/indicatorZYV')
models.Оценки_зун                           = require('../models/ocenkyZYN')
models.Оценки_основных_лп                   = require('../models/ocenkyOsnovnyxLP')
models.Оценки_зув                           = require('../models/ocenkyZYV')
models.Активность                           = require('../models/activnost')
models.Объект_контроля_зув                  = require('../models/objectControlyaZYV')
models.Эпитеты                              = require('../models/epitety')
models.Переменные                           = require('../models/peremennie')
models.Виды_переменных                      = require('../models/vidyPeremennyx')
models.Правила                              = require('../models/pravila')
models.Компоненты_правил                    = require('../models/componentyPravil')
//////ASSOCIATE///////
/*
models.Пользователь.hasOne(models.Студент,{onDelete:'cascade'})
models.Направление.hasMany(models.Студент,{onDelete:'cascade'})
models.Направление.hasOne(models.Учебные_дисциплины,{onDelete:'cascade'})
models.Направление.hasOne(models.Компетенция,{onDelete:'cascade'})
models.Компетенция.hasOne(models.Индикаторы_достижения_компетенций,{onDelete:'cascade'})
models.Компетенция.hasOne(models.Оценки_компетенций,{onDelete:'cascade'})
//models.Индикаторы_достижения_компетенций.hasOne(models.Контрольные_задания,{onDelete:'cascade'})
models.Индикаторы_достижения_компетенций.hasOne(models.Оценки_индикаторов,{onDelete:'cascade'})
models.Контрольные_задания.hasOne(models.Оценки_кз,{onDelete:'cascade'})
models.Контрольные_задания.hasOne(models.Нечеткая_классфикация_зув,{onDelete:'cascade'})
models.Оценки_компетенций.hasOne(models.Термы_и_область_определения,{onDelete:'cascade'})
models.Термы_и_область_определения.hasOne(models.Оценки_индикаторов,{onDelete:'cascade'})
*/


module.exports = models